version: '3.9'
services:
  api:
    build:
      context: ./packages/api
    ports:
      - "4100:4100"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:4100/health"]
      interval: 10s
      timeout: 2s
      retries: 5
    restart: unless-stopped
  web:
    build:
      context: ./apps/web
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:4100
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:3000"]
      interval: 15s
      timeout: 3s
      retries: 5
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

