import { TcmsDefinition } from './types';

export const TCMS_TAXONOMY: Record<string, TcmsDefinition> = {
  TRAC_INV_OVHT: {
    system: 'TRACTION',
    code: 'TRAC_INV_OVHT',
    title: 'Traktionsumrichter: Übertemperatur',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Traktionsumrichter über Temperaturgrenze (gemessen {temp}°C)',
    typicalCauses: ['Kühlkreislauf reduziert', 'Lüfterausfall', 'Dauerlast im Steilstück'],
    suggestedActions: [
      'Leistungsanforderung reduzieren',
      'Lüfter prüfen',
      'Kühlmittelkreislauf inspizieren',
    ],
  },
  BRAKE_MAIN_AIR_LOW: {
    system: 'BRAKE',
    code: 'BRAKE_MAIN_AIR_LOW',
    title: 'Brems-Hauptluftleitung: Druck zu niedrig',
    defaultSeverity: 'CRITICAL',
    humanTemplate: 'Hauptluftleitung < {bar} bar – Bremsleistung eingeschränkt',
    typicalCauses: ['Leckage HLL', 'Kompressor-Störung', 'Ventil klemmt'],
    suggestedActions: [
      'Zug anhalten, Dichtheit prüfen',
      'Kompressorstatus checken',
      'Ventile wartungsseitig prüfen',
    ],
  },
  WSP_ACTIVE_EXCESS: {
    system: 'WSP',
    code: 'WSP_ACTIVE_EXCESS',
    title: 'Radschlupfregelung: Häufig aktiv',
    defaultSeverity: 'WARN',
    humanTemplate: 'WSP > {events}/min aktiv – Haftwert kritisch',
    typicalCauses: ['Nässe/Laub', 'Bremsrechner-Sensorabweichung'],
    suggestedActions: ['Fahrweise anpassen', 'Radsatzlast/Belag prüfen'],
  },
  DOOR_2L_OBSTRUCTED: {
    system: 'DOOR',
    code: 'DOOR_2L_OBSTRUCTED',
    title: 'Tür 2L: Hindernis erkannt',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Tür 2L schließt nicht – Hindernis/Quetschutz ausgelöst',
    typicalCauses: ['Objekt im Türbereich', 'Sensor fehlkalibriert'],
    suggestedActions: ['Türbereich räumen', 'Tür neu ansteuern', 'Sensor prüfen'],
  },
  DOOR_3R_LOCK_TIMEOUT: {
    system: 'DOOR',
    code: 'DOOR_3R_LOCK_TIMEOUT',
    title: 'Tür 3R: Verriegelung Timeout',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Tür 3R verriegelt nicht innerhalb Frist',
    typicalCauses: ['Verriegelungsmechanik schwergängig', 'Steuergerät verzögert'],
    suggestedActions: ['Tür manuell prüfen', 'Mechanik schmieren', 'Aktuator inspizieren'],
  },
  HVAC_COMP_OVCUR: {
    system: 'HVAC',
    code: 'HVAC_COMP_OVCUR',
    title: 'HVAC Kompressor: Überstrom',
    defaultSeverity: 'ALARM',
    humanTemplate: 'HVAC Kompressor überstrom – Phase {phase}, {amps} A',
    typicalCauses: ['Kompressor klemmt', 'Leistungsmodul defekt'],
    suggestedActions: ['Kompressor abschalten', 'Leistungsteil prüfen'],
  },
  HVAC_CAB_TEMP_SENSOR_FAIL: {
    system: 'HVAC',
    code: 'HVAC_CAB_TEMP_SENSOR_FAIL',
    title: 'HVAC Kabinentemperatursensor: Ausfall',
    defaultSeverity: 'WARN',
    humanTemplate: 'Kabinentemperatursensor liefert ungültige Werte',
    typicalCauses: ['Sensor defekt/Stecker lose', 'Leitungsbruch'],
    suggestedActions: ['Sensor ersetzen', 'Leitungsprüfung'],
  },
  PANTO_NO_RISE: {
    system: 'PANTOGRAPH',
    code: 'PANTO_NO_RISE',
    title: 'Pantograph hebt nicht',
    defaultSeverity: 'CRITICAL',
    humanTemplate: 'Panto-Hebebefehl ohne Bewegung – Druck {bar} bar',
    typicalCauses: ['Pneumatikdruck zu gering', 'Verriegelung klemmt'],
    suggestedActions: ['Druckversorgung prüfen', 'Mechanik prüfen', 'Ersatzlok/Abschleppkonzept'],
  },
  PANTO_ARC_DETECTED: {
    system: 'PANTOGRAPH',
    code: 'PANTO_ARC_DETECTED',
    title: 'Lichtbogen detektiert',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Lichtbogen am Stromabnehmer – Spannungsspitze {kv} kV',
    typicalCauses: ['Verschmutzung Fahrdraht', 'Kontaktproblem'],
    suggestedActions: ['Leistung reduzieren', 'Inspektion Panto/Kohle'],
  },
  BAT_VOLT_LOW: {
    system: 'BATTERY',
    code: 'BAT_VOLT_LOW',
    title: 'Batteriespannung niedrig',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Batteriespannung < {volts} V – DC/Hilfsnetze gefährdet',
    typicalCauses: ['Ladegerät defekt', 'Batterie-Alterung'],
    suggestedActions: ['Ladegerät prüfen', 'Batterietest durchführen'],
  },
  NET_MVB_BUS_OFF: {
    system: 'NETWORK',
    code: 'NET_MVB_BUS_OFF',
    title: 'MVB: Bus Off',
    defaultSeverity: 'ALARM',
    humanTemplate: 'Feldbus MVB im Zustand BUS-OFF – Segment {seg}',
    typicalCauses: ['Kurzschluss/Reflexion', 'Teilnehmer defekt'],
    suggestedActions: ['Segmentprüfung', 'Teilnehmer trennen/tauschen'],
  },
  NET_ETH_LINK_LOSS: {
    system: 'NETWORK',
    code: 'NET_ETH_LINK_LOSS',
    title: 'Ethernet: Link Loss',
    defaultSeverity: 'WARN',
    humanTemplate: 'Ethernet-Link Down – Port {port}',
    typicalCauses: ['Kabel/Stecker', 'Switch Port down'],
    suggestedActions: ['Patchkabel tauschen', 'Switch prüfen'],
  },
  PIS_CTRL_RESTARTED: {
    system: 'PIS',
    code: 'PIS_CTRL_RESTARTED',
    title: 'FIS-Controller neu gestartet',
    defaultSeverity: 'INFO',
    humanTemplate: 'FIS-Controller Neustart abgeschlossen ({reason})',
    typicalCauses: ['Software-Update', 'Watchdog'],
    suggestedActions: ['Version prüfen', 'Monitoring'],
  },
  CCTV_CAM05_NO_SIGNAL: {
    system: 'CCTV',
    code: 'CCTV_CAM05_NO_SIGNAL',
    title: 'CCTV Kamera 05: Kein Signal',
    defaultSeverity: 'WARN',
    humanTemplate: 'CCTV Cam 05 ohne Videosignal',
    typicalCauses: ['Kabel/Stecker locker', 'Kamera defekt'],
    suggestedActions: ['Stecker prüfen', 'Kameratausch'],
  },
  SANDER_LOW_LEVEL: {
    system: 'SANDER',
    code: 'SANDER_LOW_LEVEL',
    title: 'Sander: Füllstand niedrig',
    defaultSeverity: 'INFO',
    humanTemplate: 'Sandfüllstand < {pct} %',
    typicalCauses: ['Abnutzung/hohe Nutzung'],
    suggestedActions: ['Bei nächster Gelegenheit nachfüllen'],
  },
};
