name: agent-policy

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run agent policy check (warn-only)
        run: node scripts/ci/agent-policy-check.mjs || true
      - name: Echo enforced process (info)
        run: |
          echo "Agents MUST run 'npm run verify' locally before pushing."
          echo "Pre-push hook enforces local verify; override with --no-verify only in emergencies."
          echo "Visual tests are disabled in CI (ENABLE_VISUAL_TESTS=0)."
          echo "Production deploy is monitored via 'deploy-production' with health + smoke checks."




