name: ci

on:
  push:
  pull_request:

jobs:
  internal-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Typecheck
        run: npm run -s typecheck || true
      - name: Lint
        run: npm run -s lint || true
      - name: Build
        run: npm run -s build || true
      - name: Test (internal only)
        run: npm run -s test:int || true
      - name: Upload logs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            **/npm-debug.log*
            **/logs/**


