name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Format check (non-blocking)
        run: npm run format:check || true
      - name: Lint (baseline, non-blocking)
        run: npm run lint:baseline || true
      - name: Build
        run: npm run build:all
      - name: Install Playwright browsers (for smoke)
        run: npx playwright install --with-deps
      - name: Smoke tests (fast, stable)
        env:
          PLAYWRIGHT_SKIP_WEBSERVER: '1'
          ENABLE_VISUAL_TESTS: '0'
        run: ENABLE_VISUAL_TESTS=0 npx playwright test tests/e2e/ci-smoke.spec.ts --project=chromium --reporter=html,line || true
      - name: Tests (optional)
        if: ${{ false }}
        run: npm run test:all


