name: Preview + Pages (one-shot)

on:
  workflow_dispatch:
  push:
    branches: [main, feat/train-tracker-p0]

permissions:
  actions: read
  contents: write
  pages: write
  id-token: write
  pull-requests: write

concurrency: preview-pages-${{ github.ref }}

jobs:
  run-all:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (npm ci)
        id: npmci
        run: npm ci
        continue-on-error: true

      - name: Install deps (fallback)
        if: steps.npmci.outcome == 'failure'
        run: npm i --prefer-offline

      - name: Preview + Perf
        run: node scripts/ci/verify-int-perf-preview.mjs || true

      - name: Build Pages State
        run: node scripts/ci/build-pages-state.mjs

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Append URLs to CHANGESUMMARY
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            try { fs.appendFileSync('CHANGESUMMARY.md', '\n'); } catch {}
            try { fs.appendFileSync('CHANGESUMMARY.md', `Pages URL: ${process.env.PAGE_URL || '${{ steps.deploy.outputs.page_url }}'}\n`); } catch {}

      - name: Upload run artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-pages-run
          path: |
            CHANGESUMMARY.md
            state/**
            docs/VC_READINESS.md
            docs/VC_DEMO_SCRIPT.md
          if-no-files-found: ignore

      - name: PR comment with links (if PR exists)
        run: node scripts/ci/post-preview-links.mjs




